modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory
license="MIT"
issueTrackerURL = "https://github.com/matthewperiut/Chisel-Reborn/issues"

[[mods]]
modId = "factory_blocks"
version = "${version}"
displayName = "Factory Blocks"
authors = "slaincow"
description = '''
Adds Factory Blocks to Chisel Reborn or Chipped
'''
logoFile = "assets/factory_blocks/icon.png"

[[dependencies.factory_blocks]]
modId="minecraft"
type="required"
versionRange="[1.21.2,)"

[[dependencies.factory_blocks]]
modId="neoforge"
type="required"
versionRange="[0,)"

[[dependencies.factory_blocks]]
modId="architectury"
type="required"
versionRange="[0,)"